server:
  port: 8889
spring:
  servlet:
    multipart:
      max-file-size: 10MB
  datasource:
    url: "jdbc:mysql://101.132.236.121:3306/music?serverTimeZone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false"
    username: root
    password: Ljh554959!
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initialSize: 1
      filters: stat
      maxActive: 2
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
  #配置年月日格式以及时区
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mail:
    default-encoding: UTF-8
    host: smtp.qq.com
    username: 2272094523@qq.com
    password: ouaawcixsdxudjee
    properties:
      mail:
        smtp:
          enable: true
  redis:
    host: 101.132.236.121
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
    lettuce:
      shutdown-timeout: 0
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ahao,java.music.pojo
logging:
  level:
    com.ahao.java.music.dao: debug


